name: mynote_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  cupertino_icons: ^1.0.8
  flutter_image_compress: ^2.3.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10
  fluttertoast: ^8.2.12
  focused_menu: ^1.0.5
  image_picker: ^1.1.2
  intl: ^0.19.0
  path_provider: ^2.1.5
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Icon.png"
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash-logo.png
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  fonts:
    - family: Montserrat Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Montserrat Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: DS Digital
      fonts:
        - asset: assets/fonts/DS-DIGIB.TTF
